cme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
# from .views import Home, CourseList, CourseDetail, AboutUs, Faq, Privacy, Terms, Disclaimer





# customizing admin interface 
admin.site.site_header = 'CME Academy'
admin.site.site_title = 'CME Academy'
admin.site.index_title = 'CME Administration'



urlpatterns = [
    # path('', Home.as_view(), name='home'),
    # path("programs/", include("courses.urls")),
    # path('about/', AboutUs.as_view(), name='about'),
    # path('faq/', Faq.as_view(), name='faq'),
    # path('privacy/', Privacy.as_view(), name='privacy'),
    # path('terms/', Terms.as_view(), name='terms'),
    # path('disclaimer/', Disclaimer.as_view(), name='disclaimer'),
    # path('courses/', CourseList.as_view(), name='courses'),
    # path('courses/detail/', CourseDetail.as_view(), name='courses-detail'), 
    # path('contact/', Contact.as_view(), name='contact'),
    # path('registration/',include('registration.urls', namespace = 'registration')),
    path('contact/',include('contact.urls', namespace = 'contact')),    
    path("courses/", include("courses.urls", namespace = 'courses')),
    path("plans/", include("plans.urls", namespace = 'plans')),
    path("affiliates/", include("affiliates.urls", namespace = 'affiliates')),
    path('payments/',include('payments.urls', namespace = 'payments')), 
    path('dashboard/',include('dashboard.urls', namespace = 'dashboard')),
    path('coupon/',include('coupon.urls', namespace = 'coupon')),
    # path('coupons/',include('coupons.urls', namespace = 'coupons')),
    path('accounts/',include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'), #auth library
    # urls handling WYSIWYG editor
    path('summernote/', include('django_summernote.urls')), 
    path('ns-admin/', admin.site.urls),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from .views import home_view, about_view, privacy_view, terms_view, disclaimer_view, sales_page_view, channel_page_view #Home, AboutUs, Privacy, Terms, Disclaimer#, CourseList, CourseDetail



urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('privacy/', privacy_view, name='privacy'),
    path('terms/', terms_view, name='terms'),
    path('disclaimer/', disclaimer_view, name='disclaimer'),
    path('community/', sales_page_view, name='sales_page'),
    path('channel/', channel_page_view, name='channel_page'),

    # path("programs/", include("courses.urls")),
    # path('about/', AboutUs.as_view(), name='about'),
    # path('faq/', Faq.as_view(), name='faq'),
    # path('privacy/', Privacy.as_view(), name='privacy'),
    # path('terms/', Terms.as_view(), name='terms'),
    # path('disclaimer/', Disclaimer.as_view(), name='disclaimer'),
    # path('contact/',include('contact.urls', namespace = 'contact')),
    
    # path("programs/", include("courses.urls", namespace = 'courses')),
    # path('courses/', CourseList.as_view(), name='courses'),
    # path('courses/detail/', CourseDetail.as_view(), name='courses-detail'),
    # path('dashboard/', home, name="dashboard"),    
    # path('contact/', Contact.as_view(), name='contact'),
    # path('accounts/',include('accounts.urls', namespace = 'accounts')),
    # path('registration/',include('registration.urls', namespace = 'registration')),
    # path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    # path('ns-admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupon/urls.py
from django.urls import path
from . import views


app_name = 'coupon'

urlpatterns = [
    path("apply/<int:payment_id>/", views.coupon_apply, name="apply"),
    # path("apply/<int:payment_id>/", views.UseCouponView.as_view(), name="apply"),
    # path("detail/<slug:slug>/", CourseDetailView.as_view(), name="detail"),
   ]

payments/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path
from . import views
# from django.views.generic import TemplateView

app_name = 'payments'

urlpatterns = [
    path('initiate/', views.payment_initiate, name='payment_initiate'),
    path('initiate/<str:payment_id>/', views.payment_coupon, name='payment_coupon'),
    path('verify/<str:ref>/', views.payment_verify, name='payment_verify'),
]



payments/models.py
from django.db import models
from decimal import Decimal
from django.conf import settings
# from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator

import secrets
from cme.decorators import CATEGORY_CHOICES, DURATION_CHOICES, FEE_STATUS
from plans.models import Plan, UserPlan
from coupon.models import Coupon 
from .paystack  import  Paystack



# # Create your models here.
# class Payments(models.Model):
#     user = models.ForeignKey(UserPlan, on_delete=models.CASCADE)
#     payment_date = models.DateField()
#     payment_period = models.IntegerField()
#     payment_amount = models.DecimalField(max_digits=12, decimal_places=2)

#     def __str__(self):
#           return self.user.username


#     class Meta:
#         abstract = False
#         verbose_name = _("Payment")
#         verbose_name_plural = _("Payments")





class UserWallet(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    currency = models.CharField(max_length=50, default='NGN')
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    date_created = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.user.__str__()





class Discount(models.Model):
    value = models.IntegerField(default=0, verbose_name="Value")
    is_percentage = models.BooleanField(default=False, verbose_name="Is percentage?")

    def __str__(self):
        if self.is_percentage:
            return "{0}%".format(self.value)

        return "₦{0}".format(self.value)




class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    category = models.CharField(choices=CATEGORY_CHOICES, default='plan', max_length=60)
    plan_type = models.CharField(max_length=60)
    duration = models.CharField(max_length=24, choices=DURATION_CHOICES, default=DURATION_CHOICES[0][0])
    ref = models.CharField(max_length=200)
    email = models.EmailField()
    coupon = models.ForeignKey(Coupon, related_name='payment_coupon', on_delete=models.CASCADE, blank=True, null=True)
    discount = models.ForeignKey(Discount, related_name='payment_discount', on_delete=models.CASCADE, blank=True, null=True)
    # discount = models.IntegerField(default=0, verbose_name="Discount Percentage", validators=[MinValueValidator(0), MaxValueValidator(100)])
    verified = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-date_created',)

    def __str__(self):
        return f"Payment: {self.amount}"


    # def get_discount_price(self):
    #     discount_price = self.amount * (self.discount / Decimal('100'))
    #     return  discount_price


    # def get_amount_payable(self):
    #     total_cost = self.amount - self.get_discount_price()
    #     return total_cost


    def get_amount_payable(self):
        if not self.coupon:
            return self.amount
        return self.coupon.get_discounted_value(self.amount)
        
    

    def amount_value(self):
        return Decimal(self.get_amount_payable()) * Decimal(100.00)
        # return Decimal(self.amount) * Decimal(100.00)
        # return int(self.amount) * 100


    def verify_payment(self):
        paystack = Paystack()
        status, result = paystack.verify_payment(self.ref, self.amount)
        if status:
            if result['amount'] /  Decimal(100.00) == self.amount:
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False


    def save(self, *args, **kwargs):
        while not self.ref:
            ref = secrets.token_urlsafe(50)
            object_with_similar_ref = Payment.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref
        # if self.coupon and not self.discount:
        #     self.
        super().save(*args, **kwargs)

payments/views.py
import datetime
import requests
from decimal import Decimal, FloatOperation
from dateutil.relativedelta import relativedelta
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse

from affiliates.models import Affiliate, UserAffiliate, AffiliateSubscription
from plans.models import Plan, UserPlan, Subscription
from .models import Payment, UserWallet
from coupon.models import Coupon, Discount
from coupon.forms import CouponApplyForm




@login_required(login_url="accounts:login")
def payment_initiate(request):

    if request.method == "POST":
        category = request.POST['category']
        plan_type = request.POST['plan_type']
        duration = request.POST['plan_duration']
        price = request.POST['plan_price']
        email = request.user.email
        user = request.user

        amount = Decimal(price)*Decimal(duration)

        payment = Payment.objects.create(amount=amount, category=category, plan_type=plan_type, duration=duration, email=email, user=user)
        payment.save()

        context = {
            'payment': payment,
            'field_values': request.POST,
            'paystack_pub_key': settings.PAYSTACK_PUBLIC_KEY,
            'amount_value': payment.amount_value(),
            'coupon_apply_form': CouponApplyForm(),
        }
        return render(request, 'payments/payment_confirmation.html', context)

    return redirect("plans:list")





@login_required(login_url="accounts:login")
def payment_coupon(request, payment_id):
    payment = get_object_or_404(Payment, id=payment_id, user__username=request.user.username)

    coupon_id = request.session['coupon_id']
    
    try:
        coupon = Coupon.objects.get(id=coupon_id)
        discount = Discount()
        discount.value = coupon.discount.value
        discount.is_percentage = coupon.discount.is_percentage
        discount.save()
        # print("=====DISCOUNT========", discount.value, coupon.discount.value, discount.is_percentage, coupon.discount.is_percentage)
        payment.coupon = coupon
        # payment.discount = discount
        payment.save()
        # print("=========valid coupon payment=============", coupon_id)
        # messages.success(self.request, "Coupon Successful")
        coupon_message = "Coupon Successful"
    except Coupon.DoesNotExist:        
        # print("=========invalid coupon payment=============", coupon_id)
        # messages.danger(self.request, "Coupon Invalid")
        coupon_message = "Coupon Invalid"
        pass

    context = {
        'payment': payment,
        'field_values': request.POST,
        'paystack_pub_key': settings.PAYSTACK_PUBLIC_KEY,
        'amount_value': payment.amount_value(),
        'coupon_apply_form': CouponApplyForm(),
        'coupon_message': coupon_message,
    }
    return render(request, 'payments/payment_confirmation.html', context)





@login_required(login_url="accounts:login")
def payment_verify(request, ref):
    payment = Payment.objects.get(ref=ref)
    verified = payment.verify_payment()

    if verified:
        category = payment.category
        # print("===Category===", category)
        if category == 'plan':
            #=== update userPlan and subscription ===#
            user_plan = UserPlan.objects.get(user=request.user)
            user_plan.plan = Plan.objects.filter(title=payment.plan_type).first()
            # user_plan.plan = payment.plan
            user_plan.save()

            subscription = Subscription.objects.get(user_plan=user_plan)
            # print("===Subscription===", subscription)
            subscription.subscription_period = payment.duration
            subscription.start_date = datetime.date.today()
            subscription.end_date = datetime.date.today() + relativedelta(months=int(payment.duration))
            subscription.amount = payment.amount 
            subscription.fee_status = 'paid'
            subscription.save()
            # print("===Sub details===", subscription.subscription_period, subscription.start_date, subscription.end_date, subscription.amount, subscription.fee_status)

        elif category == 'affiliate':
            #=== update userPlan and subscription ===#
            user_affiliate, created = UserAffiliate.objects.get_or_create(
                user=request.user,
                defaults={'affiliate': Affiliate.objects.filter(title=payment.plan_type).first()},
            )
            user_affiliate.create_code()
            user_affiliate.save() 
            # print("===User Affiliate===", user_affiliate)

            subscription, created = AffiliateSubscription.objects.get_or_create(
                user_affiliate=user_affiliate,
                defaults={
                    'subscription_period': payment.duration,
                    'start_date': datetime.date.today(),
                    'end_date': datetime.date.today() + relativedelta(months=int(payment.duration)),
                    'amount': payment.amount,
                    'fee_status': 'paid',
                },
            )
            # print("===Subscription===", subscription)

        else:
            raise Http404

        # #=== update user-wallet ===#
        # user_wallet = UserWallet.objects.get(user=request.user)
        # user_wallet.balance += payment.amount
        # user_wallet.save()
        
        # print(request.user.username, " funded wallet successfully")
  
        # # To display cryptocurrency current prices on top of the navbar
        # try:
        #     url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=100&page=1&sparkline=false'
        #     data = requests.get(url).json()
        # except:
        #     data = []

        # context = {
        #     'data': data,
        # }

        # return render(request, "payments/payment_successful.html", {})
    return render(request, "payments/payment_successful.html", {})

templates/payments/payment_confirmation.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}



  {% block css %}
  <script src="https://js.paystack.co/v1/inline.js"></script>
  {% endblock css %}

  {% block content %}
 

    {% include 'inlines/header-pages.html' %}


 <!-- {# <script src="https://js.paystack.co/v1/inline.js"></script> #} -->

	<div class="services section pricing" id="services">
		<div class="container">
	        <div class="row text-center">
	            <div class="col-sm-6 offset-sm-3">
	                <div class="heading-section">
	                    <h2 class="text-orange pb-5"><span>{{ payment.get_category_display }} Payment</span></h2>
	                    	<div class="table-responsive ">
												  <table class="table table-bordered">
												  	<tr class="left">
													    <td class="font-weight-bold">{{ payment.get_category_display }}:</td>
													    <td>{{ payment.plan_type|title }} </td>
													  </tr>
												  	<tr>
													    <td class="font-weight-bold">Duration:</td>
													    <td>{{ payment.duration }} months</td>
													  </tr>
														{% if payment.coupon %}
														<div class="text-sm">
													  	<tr class="text-sm">
														    <td class="font-weight-bold">Subtotal:</td>
														    <td>&#8358;{{ payment.amount|floatformat:"0"|intcomma }}</td>
														  </tr>
													  	<tr class="small">
														    <td class="">Coupon:</td>
														    <td class="text-muted">{{ payment.coupon.code }} <br>({{ payment.coupon.discount|intcomma }} Off)</td>
														  </tr>
													  	<!-- <tr class="small">
														    <td class="">Discount:</td>
														    <td class="text-muted">- &#8358;{{ payment.amount|intcomma }}</td>
														  </tr> -->
														</div>
														{% endif %}
												  	<tr class="lead">
													    <td class="font-weight-bold text-uppercase">Total:</td>
													    <td class="font-weight-bold">&#8358;{{ payment.get_amount_payable|floatformat:"0"|intcomma }}</td>
													  </tr>
												  </table>
												</div> 
												<br>
													
												<div class="mb-4">
													<!-- <p>Apply a coupon:</p> -->
													<form action="{% url 'coupon:apply' payment.id %}" method="post">
														{% csrf_token %}
														{{ coupon_apply_form }}
														<input class="btn-secondary btn-sm" type="submit" value="{% trans 'Apply' %}">
													</form>
													{% if coupon_message %}
														<p class="text-primary py-0">{{ coupon_message }}</p>
													{% endif %}
												</div>

											<br>
											<button onclick="payWithPaystack()" class="btn btn-lg btn-orange px-5"><span class="lead text-sm font-weight-bold">Proceed to Pay</span></button>
	                </div>
	            </div>
	        </div>
		</div>
	</div>

	<script>
		function payWithPaystack() {
			let currency = "NGN";
			let plan = "";
			let ref = "{{ payment.ref }}";
			let amount = "{{ payment.get_amount_payable }}";
			let obj = {
				key: "{{ paystack_pub_key }}",
				email: "{{ payment.email }}",
				amount: "{{ amount_value }}",
				ref: ref,
				callback: function (response) {
					window.location.href = "{% url 'payments:payment_verify' payment.ref %}";
				},
			};
			if (Boolean(currency)) {
				obj.currency = currency.toUpperCase();
			}
			if (Boolean(plan)) {
				obj.plan - plan;
			}

			var handler = PaystackPop.setup(obj);
			handler.openIframe();
		}
	</script>




    {% include 'inlines/footer.html' %}



  {% endblock content %}
	




	

templates/payments/payment_successful.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}



  {% block css %}
  <script src="https://js.paystack.co/v1/inline.js"></script>
  {% endblock css %}

  {% block content %}
 

    {% include 'inlines/header-pages.html' %}



		<div class="services section pricing" id="services">
			<div class="container">
        <div class="row text-center">
          <div class="col-sm-6 offset-sm-3">
            <div class="heading-section">
            	<i class="fa fa-check-circle fa-5x text-success mb-3"></i>
                <h2><span>Payment Successful</span></h2>
                {% if message %}
                <p class="lead text-dark"><span class="">{{ message }}</span> </p>
								{% endif %}
								<p class="lead py-2">Dear <span class="">{{ request.user.get_full_name }}</span></p>
								<p class="lead py-2"><span class="font-weight-bold">Transaction Successful</span> </p>
								<br>
                <a href="{% url 'dashboard:home' %}" class="btn btn-lg btn-orange px-5"><i class="fa fa-arrow-left"></i> Back to Dashboard</a>
            </div>
          </div>
        </div>
			</div>
		</div>


    {% include 'inlines/footer.html' %}



  {% endblock content %}
	




	

	