cme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
# from .views import Home, CourseList, CourseDetail, AboutUs, Faq, Privacy, Terms, Disclaimer





# customizing admin interface 
admin.site.site_header = 'CME Academy'
admin.site.site_title = 'CME Academy'
admin.site.index_title = 'CME Administration'



urlpatterns = [
    # path('', Home.as_view(), name='home'),
    # path("programs/", include("courses.urls")),
    # path('about/', AboutUs.as_view(), name='about'),
    # path('faq/', Faq.as_view(), name='faq'),
    # path('privacy/', Privacy.as_view(), name='privacy'),
    # path('terms/', Terms.as_view(), name='terms'),
    # path('disclaimer/', Disclaimer.as_view(), name='disclaimer'),
    # path('courses/', CourseList.as_view(), name='courses'),
    # path('courses/detail/', CourseDetail.as_view(), name='courses-detail'), 
    # path('contact/', Contact.as_view(), name='contact'),
    # path('registration/',include('registration.urls', namespace = 'registration')),
    path('contact/',include('contact.urls', namespace = 'contact')),    
    path("courses/", include("courses.urls", namespace = 'courses')),
    path("plans/", include("plans.urls", namespace = 'plans')),
    path("affiliates/", include("affiliates.urls", namespace = 'affiliates')),
    path('payments/',include('payments.urls', namespace = 'payments')), 
    path('dashboard/',include('dashboard.urls', namespace = 'dashboard')),
    path('coupon/',include('coupon.urls', namespace = 'coupon')),
    # path('coupons/',include('coupons.urls', namespace = 'coupons')),
    path('accounts/',include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'), #auth library
    # urls handling WYSIWYG editor
    path('summernote/', include('django_summernote.urls')), 
    path('ns-admin/', admin.site.urls),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

dashboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from .views import *



app_name = 'dashboard'

urlpatterns = [
    path('', dashboard_view, name='home'),
    path('profile/', profile_view, name='profile'),
    path('courses/', course_list_view, name='course_list'),
    path("courses/<slug:slug>/", course_detail_view, name="course_detail"),
    # path("courses/pdf/<slug:slug>/", pdf_view, name="course_pdf"),

    path('messages/', message_view, name='message_list'),
    path('plans/', plans_view, name='plans'),
    path('affiliate/', affiliate_view, name='affiliate'),
    path('settings/faqs/', faqs_view, name='faqs'),
    path('settings/contact/', HelpCenterView.as_view(), name='contact'),
    path('settings/contact/sent/', message_sent, name="message_sent"),
    # path('settings/contact/', ContactCreateView.as_view(), name="contact"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payments/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
# from django.contrib import admin
from django.urls import path
from . import views
# from django.views.generic import TemplateView

app_name = 'payments'

urlpatterns = [
    path('initiate/', views.payment_initiate, name='payment_initiate'),
    path('initiate/<str:payment_id>/', views.payment_coupon, name='payment_coupon'),
    path('verify/<str:ref>/', views.payment_verify, name='payment_verify'),
]



dashboard/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings





# class Contact(models.Model):
#     last_name = models.CharField(max_length=60)
#     first_name = models.CharField(max_length=60)
#     phone = models.CharField(max_length=14)
#     email = models.EmailField()
#     company = models.CharField(max_length=120, blank=True, null=True)
#     subject = models.CharField(max_length=120)
#     message = models.TextField()
#     updated = models.DateTimeField(auto_now=True, auto_now_add=False)
#     timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

#     # objects = ContactManager()

#     class Meta:
#         ordering = ["-timestamp", "last_name"]
#         verbose_name = "Contact"
#         verbose_name_plural = "Contacts"

#     def __str__(self):
#         return "%s - %s" %(self.last_name, self.first_name)

#     def get_absolute_url(self):
#         return reverse("contact:detail", kwargs={"pk": self.pk})






class HelpCenter(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    subject = models.CharField(max_length=120)
    message = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    # objects = ContactManager()

    class Meta:
        ordering = ["-timestamp",]
        verbose_name = "Help Center"
        verbose_name_plural = "Help Center"

    def __str__(self):
        return "%s - %s" %(self.user, self.subject)

    def get_absolute_url(self):
        return reverse("contact:detail", kwargs={"pk": self.pk})

dashboard/views.py
import requests
from datetime import timedelta
from django.utils import timezone
from django.contrib import messages
from django.http import Http404, HttpResponse, FileResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import View
from django.views.generic.base import RedirectView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormMixin
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required, user_passes_test

from cme.mixins import (
    # LoginRequiredMixin, 
    # StaffRequiredMixin, 
    # ICTStaffRequiredMixin,
    # MedicalStaffRequiredMixin, 
    # AjaxRequiredMixin,
    SubmitBtnMixin,
    # FilterMixin
    ) 

from plans.models import Plan, UserPlan, Subscription
from affiliates.models import Affiliate, UserAffiliate, AffiliateSubscription
from courses.models import Course
from .models import HelpCenter
from .forms import ProfileForm, HelpCenterForm



@login_required
def dashboard_view(request):
  try:
    url = 'https://api.coingecko.com/api/v3/coins/markets?vs_currency=USD&order=market_cap_desc&per_page=100&page=1&sparkline=false'
    data = requests.get(url).json()
  except:
    data = []
  
  # return HttpResponse(data)

  context = {'data': data}

  return render(request, 'dashboard/index.html', context)



@login_required
def profile_view(request):
  
  if request.method == 'POST':
    form = ProfileForm(data=request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        # return redirect('dashboard:message_sent')
        messages.success(request, "Profile updated successfully!")
  else:
    form = ProfileForm(instance=request.user)

  context = {
    'user': request.user,
    'form': form,
    'submit_btn': 'Update Profile',
    } 

  return render(request, 'dashboard/settings-profile.html', context)






@login_required
def message_view(request):
  context = {
    'user': request.user
    }

  return render(request, 'dashboard/message-list.html', context)



@login_required
def faqs_view(request):
  context = {
    'user': request.user
    }

  return render(request, 'dashboard/settings-faqs.html', context)


@login_required
def contact_view(request):
  context = {
    'user': request.user
    }

  return render(request, 'dashboard/settings-contact.html', context)


# @login_required
# def profile_view(request):
#   context = {
#     'user': request.user
#     }

#   return render(request, 'dashboard/settings-profile.html', context)






# def pdf_view(request):
#     try:
#         return FileResponse(open('foobar.pdf', 'rb'), content_type='application/pdf')
#     except FileNotFoundError:
#         raise Http404()



# def pdf_view(request):
#   try:
#       return FileResponse(open('foobar.pdf', 'rb'), content_type='application/pdf')
#   except FileNotFoundError:
#       raise Http404()





@login_required
def course_list_view(request):
  grade_0 = grade_1 = grade_2 = grade_3 = []
  try:
    if request.user.is_authenticated:
      user_plan = UserPlan.objects.filter(user=request.user).first()
      user_subscription = Subscription.objects.filter(user_plan=user_plan).first()

      if user_plan and user_subscription and user_subscription.is_active() and not user_subscription.is_expired():

        if user_plan.plan.title == "free":
          grade_0 = Course.objects.all().filter(plan__title='free')
        elif user_plan.plan.title == "basic":
          grade_0 = Course.objects.all().filter(plan__title='free')
          grade_1 = Course.objects.all().filter(plan__title='basic')
        elif user_plan.plan.title == "advance":
          grade_0 = Course.objects.all().filter(plan__title='free')
          grade_1 = Course.objects.all().filter(plan__title='basic')
          grade_2 = Course.objects.all().filter(plan__title='advance')
        elif user_plan.plan.title == "pro":
          grade_0 = Course.objects.all().filter(plan__title='free')
          grade_1 = Course.objects.all().filter(plan__title='basic')
          grade_2 = Course.objects.all().filter(plan__title='advance')
          grade_3 = Course.objects.all().filter(plan__title='pro')
        else:
          pass
          # grade_0 = grade_1 = grade_2 = grade_3 = []

    # query = request.GET.get("search")
    # if query:
    #   qs = qs.filter(
    #           Q(title__iexact=query)|
    #           Q(description__icontains=query)
    #           ).distinct()
  except:
    pass


  context = {
    # "object_list": qs,
    "course_list": Course.objects.all(),
    "grade_0": grade_0,
    "grade_1": grade_1,
    "grade_2": grade_2,
    "grade_3": grade_3,
    }
  return render(request, 'dashboard/course-list.html', context)





@login_required
def course_detail_view(request, slug):
  obj = get_object_or_404(Course, slug=slug)

  if request.user.is_authenticated:
    user_plan = UserPlan.objects.filter(user=request.user).first()
    user_subscription = Subscription.objects.filter(user_plan=user_plan).first()
    if user_plan and not user_subscription.is_expired() and user_subscription.is_active():

      if user_plan.get_user_grade() < obj.get_course_grade():
        # raise Http404()
        context = {
          "content": "You are not registered for this course!"
          }
        return render(request, 'dashboard/static-page.html', context)
    else:        
      # raise Http403()
      context = {
          "content": "You are not registered for this course!"
        }
      return render(request, 'dashboard/static-page.html', context)

  
  context = {
    "object": obj,
    "course_list": Course.objects.all(),
    }
  return render(request, 'dashboard/course-detail.html', context)






# from django.shortcuts import render
# from django.http import FileResponse, Http404





# import os
# from django.http import FileResponse, Http404


# def pdf_view(request, slug):
#   obj = get_object_or_404(Course, slug=slug)
#   print("===PDF URL===", obj.upload_file.url)
#   pdf_path = '127.0.0.1:8003%s' %(obj.upload_file.url)
#   file_path = r'127.0.0.1:8003%s' %(obj.upload_file.url)
#   print("===PDF EXIST===", os.path.isfile(file_path), file_path)
#   print("===PDF PATH===", '%s' %(pdf_path))
#   try:
#     return FileResponse(open(f'{pdf_path}', 'rb'), content_type='application/pdf')
#   except FileNotFoundError:
#     raise Http404()


# file_path = r'C:\Users\myname\Rprojects\Reports_scraping\data_scraped\icnarc_29052020\icnarc_200529.pdf'
# print( os.path.isfile(file_path))



# def pdf_view(request, slug):
#   obj = get_object_or_404(Course, slug=slug)
#   print("===PDF URL===", obj.upload_file.url)
#   pdf_path = '127.0.0.1:8003%s' %(obj.upload_file.url)
#   file_path = r'127.0.0.1:8003%s' %(obj.upload_file.url)
#   print("===PDF EXIST===", os.path.isfile(file_path), file_path)
#   print("===PDF PATH===", f'{pdf_path}')
#   with open('%s' %(pdf_path), 'rb') as pdf:
#     response = HttpResponse(pdf.read(),content_type='application/pdf')
#     response['Content-Disposition'] = 'filename=upload_file.pdf'
#     return response


# content = f"inline; filename={filename}"


# def pdf_view(request, slug):
#   obj = get_object_or_404(Course, slug=slug)
#   print("===PDF File===", 'obj.upload_file')
#   pdf_path = "obj.upload_file.url"
#   with open(pdf_path, 'rb') as pdf:
#     response = HttpResponse(pdf.read(), mimetype='application/pdf')
#     response['Content-Disposition'] = 'inline; filename=upload_file_name.pdf'
#     return response
#   pdf.closed






# def pdf_view(request, slug):
#   obj = get_object_or_404(Course, slug=slug)
#   # try:
#   #     return FileResponse(open('<file name with path>', 'rb'), content_type='application/pdf')
#   # except FileNotFoundError:
#   #     raise Http404('not found')

#   try:
#       return FileResponse(open(obj.upload_file, 'rb'), content_type='application/pdf')
#   except FileNotFoundError:
#       raise Http404()


# def pdf_view(request, slug):
#   obj = get_object_or_404(Course, slug=slug)
#   with open(obj.upload_file, 'rb') as pdf:
#     response = HttpResponse(pdf.read(),content_type='application/pdf')
#     response['Content-Disposition'] = 'filename=some_file.pdf'
#     return response








@login_required
def plans_view(request):
  plan_list = Plan.objects.exclude(title="free")
  current_plan = []
  try:
    if request.user.is_authenticated:
      user_plan = UserPlan.objects.filter(user=request.user).first()
      user_subscription = Subscription.objects.filter(user_plan=user_plan).first()
      # if user_plan is not None and not user_subscription.is_expired() and user_subscription.is_active():
      if user_plan is not None and user_subscription is not None and not user_subscription.is_expired() and user_subscription.is_active():
        current_plan = user_plan.plan #UserPlan.objects.filter(plan__title="free").first()
  except:
    pass

  context = {
    "category": "plan",
    "current_plan": current_plan,
    "object_list": plan_list,
    }

  return render(request, 'dashboard/plan-list.html', context)




@login_required
def affiliate_view(request):
  plan_list = Affiliate.objects.exclude(title="free")

  current_plan = []
  try:
    if request.user.is_authenticated:
      user_plan = UserAffiliate.objects.filter(user=request.user).first()
      user_subscription = AffiliateSubscription.objects.filter(user_affiliate=user_plan).first()
      if user_plan and user_subscription and not user_subscription.is_expired() and user_subscription.is_active():
        current_plan = user_plan # UserAffiliate.objects.filter(affiliate__title="free").first()
      # print("=====", user_subscription.is_expired(), "ACTIVE", user_subscription.is_active())
  except:
    pass

  context = {
      'category': 'affiliate',
      'current_plan': current_plan,
      'object_list': plan_list
    }

templates/dashboard/affiliate-list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}


{% block css %}
  <style type="text/css">
    li {
      padding-bottom: 8px;
    }
  </style>
{% endblock css %}







{% block content %}
  <div class="container-fluid">

    {% if current_plan %}
    <div class="row justify-content-center mb-4">
      <div class="col-12">
        <h3>Welcome Affiliate</h3>
        <p class="lead text-dark">Grow Your Earnings Significantly</p>
        <div class="card-deck my-4">
          <div class="card col-sm-6 mb-4 shadow">
            <div class="card-body my-4">
              <h3 class="h5 text-orange my-4">Your Affiliate Details:</h3>
              <p class="text-muted lead"><span class="font-weight-bold">Referer Code:</span> &nbsp; <span class="text-primary">{{ current_plan.referer_code }}</span></p>
              <p class="text-muted lead">
                <span class="font-weight-bold">Referer Link:</span> &nbsp; 
                <input type="text" class="form-control" value="www.joincme.com/accounts/register/?ref={{ current_plan.referer_code }}" id="myInput" disabled> 
                <button class="btn btn-sm btn-secondary my-2" onclick="myFunction()">Copy link</button>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}


    <div class="row justify-content-center">
      <div class="col-12">
        <h3>Become an Affiliate</h3>
        <!-- <p class="lead text-dark">Grow Your Earnings Significantly</p> -->
        <p class="lead text-dark">Get access to the biggest network of digital product creators and earn money when you recommend their products to your audience.</p>
        <div class="card-deck my-4">
          {% for object in object_list %}
          <div class="card col-sm-6 mb-4 shadow">
            <div class="card-body text-center my-4">
              <h3 class="h5 text-orange my-4">Affiliate Network</h3>
              <p class="text-muted">This plan offers more. A plan that gives you access to the biggest network of traders, and sets you up for financial independence.</p>
              <span class="h1 mb-0">&#8358;{{ object.price|floatformat:"0"|intcomma }}</span>
              <p class="text-muted">per month</p>
              <hr>
              {% if object.title == current_plan.affiliate.slug %}
              <span class="dot dot-lg bg-success"></span>
              <span class="font-weight-bold text-uppercase ml-3">Active</span>
              {% else %}
              <form method="POST" action="{% url 'payments:payment_initiate' %}">{% csrf_token %}
                <input type="hidden" name="category" value="{{ category }}">
                <input type="hidden" name="plan_type" value="{{ object.title }}">
                <input type="hidden" name="plan_price" value="{{ object.price }}">
                <input type="hidden" name="plan_duration" value="12"> 
                <br>
                <button type="submit" class="btn btn-orange btn-lg mb-2">Get 1-Year Plan</button>
              </form>
              {% endif %}
            </div> <!-- .card-body -->
          </div>
          {% endfor %}
          <!-- .card -->
        </div> <!-- .card-group -->
      </div> <!-- /.col -->
    </div> <!-- .row -->
  </div> 
{% endblock content %}


{% block script %}
<script>
function myFunction() {
  // Get the text field
  var copyText = document.getElementById("myInput");

  // Select the text field
  copyText.select();
  copyText.setSelectionRange(0, 99999); // For mobile devices

   // Copy the text inside the text field
  navigator.clipboard.writeText(copyText.value);

  // Alert the copied text
  alert("Link Copied:   " + copyText.value);
}
</script>
{% endblock script %}

templates/dashboard/message-list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}


{% block css %}
  <style type="text/css">
    li {
      padding-bottom: 8px;
    }
  </style>
{% endblock css %}


{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-12 col-xl-12">
        <h3 class="h3">Messages</h3>
        <p class="text-dark lead">You have (0) messages.</p>
        <div class="my-4">

        </div>
      </div>
    </div>
  </div> 
{% endblock content %}

templates/dashboard/settings-contact-sent.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}


{% block css %}
  <style type="text/css">
    li {
      padding-bottom: 8px;
    }
  </style>
{% endblock css %}


{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10 col-xl-10">
        <h3>Message Sent</h3>
        <div class="my-4">
          <div class="row align-items-center">
            <div class="col-md-12">
              <p class="h5 text-muted">Your message was sent successfully.</p>
              <p class="text-mute">Thank you for contacting us, our support center will get back to you as soon as possible.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
{% endblock content %}

templates/dashboard/settings-contact.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}


{% block css %}
  <style type="text/css">
    li {
      padding-bottom: 8px;
    }
  </style>
{% endblock css %}


{% block content %}


{% comment %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12">
        <h3>Contact Us</h3>
        <p class="lead text-dark">Feel free to contact us anytime</p>
        <div class="card-deck my-4">
          <div class="card col-sm-6 mb-4 shadow">
            <div class="card-body my-4">
              <h3 class="h5 text-orange my-4">Contact Support</h3>
              <p class="mb-4">We introduce people to the world of trading crypto through our non-drowsy educational content and tools. We're also a community of traders that support each other on our daily trading journey.</p>
              <p class=""><span class="text-dark font-weight-bold text-uppercase">Phone:</span> +234-803-111-2222</p>
              <p class=""><span class="text-dark font-weight-bold text-uppercase">Email:</span> support@joincme.com</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
{% endcomment %}






  <div class="container-fluid">
      <div class="row mb-5 justify-content-center">
        <div class="col-12 col-xl-8">
          <form action="." method="POST">{% csrf_token %}
            <hr class="my-4">
            <h2 class="h2 mb-2 mt-4">Get in <span>touch</span></h2>
            <p class="lead mb-4">Reach our help centre anytime, anywhere or everyday to get assistance using our services.</p>
            <hr>
            {% if form.non_field_errors %}
              <div class="small text-danger"> {{ form.non_field_errors }}</div>
            {% endif %}
                              
            {% for field in form %}
            <div class="form-row">
              <div class="form-group col-md-12">
                <label class="mb-0 mt-2">{{ field.label_tag }} {% if field.field.required %}<span class="text-danger">*</span>{% endif %}</label>
                {{ field }}
                {% if field.help_text %}
                    <small class="text-muted">{{ field.help_text|safe }}</small>
                {% endif %}
                <small class="text-danger">{{ field.errors }}</small>
              </div>
              <!-- /.form-group -->
            </div>
            {% endfor %}
            <div class="form-row my-4">
              <div class="col">
                  <button type="submit" class="btn btn-orange"> {% if submit_btn %}{{ submit_btn }}{% else %} Submit Form {% endif %}</button>
              </div>
              <div class="col-auto">
                  <button type="button" class="btn btn-secondary" onclick="window.history.back();">Cancel</button>
              </div>
            </div>
          </form>
        </div>
      </div>
  </div> 
{% endblock content %}



            <form id="contact-form" method="POST" action="{% url 'contact:contact' %}">{% csrf_token %}
              <div class="row">
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="fullname" id="fullname" value="{{ fullname }}" placeholder="Full name" autocomplete="on" required>
                    <span class="small text-white"><i>{{ c_form.fullname.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="phone" id="phone" value="{{ phone }}" pattern="+234" placeholder="Phone number" required="">
                    <span class="small text-white"><i>{{ c_form.phone.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="email" id="email" value="{{ email }}" pattern="[^ @]*@[^ @]*" placeholder="E-mail address" required="">
                    <span class="small text-white"><i>{{ c_form.email.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <textarea name="message" id="message" placeholder="Your Message">{{ message }}</textarea>
                    <span class="small text-white"><i>{{ c_form.message.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                  </fieldset>
                </div>
              </div>
            </form>

templates/dashboard/static-page.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load static %}
{% load humanize %}


{% block css %}
  <style type="text/css">
    li {
      padding-bottom: 8px;
    }
  </style>
{% endblock css %}


{% block content %}
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12 col-lg-10 col-xl-10">
        <h3>Courses</h3>
        <div class="my-4">
          <div class="row align-items-center">
            <div class="col-md-12">
              <p class="h4 mb-4 text-orange">{{ content }}</p>
              <a href="{% url 'dashboard:course_list' %}" class="btn btn-lg btn-outline-secondary px-5"> View Courses </a>
              <a href="{% url 'dashboard:plans' %}" class="btn btn-lg btn-outline-success px-5 mx-5"> Upgrade Plan </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div> 
{% endblock content %}




  <div class="col-md-4 mb-4">
    <div class="card shadow">
      <div class="card-body">
        <p class="card-title"><strong>Default Modal</strong></p>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <!-- Button trigger modal -->
        <button type="button" class="btn mb-2 btn-primary" data-toggle="modal" data-target="#defaultModal"> Launch demo modal </button>
        <!-- Modal -->
        <div class="modal fade" id="defaultModal" tabindex="-1" role="dialog" aria-labelledby="defaultModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="defaultModalLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla dui urna, cursus mollis cursus vitae, fringilla vel augue. In vitae dui ut ex fringilla consectetur. Sed vulputate ante arcu, non vehicula mauris porttitor quis. Praesent tempor varius orci sit amet sodales. Nullam feugiat condimentum posuere. Vivamus bibendum mattis mi, vitae placerat lorem sagittis nec. Proin ac magna iaculis, faucibus odio sit amet, volutpat felis. Proin eleifend suscipit eros, quis vulputate tellus condimentum eget. Maecenas eget dui velit. Aenean in maximus est, sit amet convallis tortor. In vel bibendum mauris, id rhoncus lectus. Suspendisse ullamcorper bibendum tellus a tincidunt. Donec feugiat dolor lectus, sed ullamcorper ante rutrum non. Mauris vestibulum, metus sit amet lobortis fringilla, dui est venenatis ligula, a euismod sem augue vel lorem. Nunc feugiat eget tortor vel tristique. Mauris lobortis efficitur ligula, et consectetur lectus maximus sed. </div>
              <div class="modal-footer">
                <button type="button" class="btn mb-2 btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn mb-2 btn-primary">Save changes</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>