accounts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
# from .views import home
from .views import register_view, login_view, logout_view #DashboardView, ProfileView, CategoryListView
from django.views.generic import TemplateView

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    # path('category/', TemplateView.as_view(template_name="dashboard/category.html")),
]


# urlpatterns = [
# path('login',views.login, name='login'),
# path('logout',views.logout, name='logout'),
# ]

cme/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
# from .views import Home, CourseList, CourseDetail, AboutUs, Faq, Privacy, Terms, Disclaimer





# customizing admin interface 
admin.site.site_header = 'CME Academy'
admin.site.site_title = 'CME Academy'
admin.site.index_title = 'CME Administration'



urlpatterns = [
    # path('', Home.as_view(), name='home'),
    # path("programs/", include("courses.urls")),
    # path('about/', AboutUs.as_view(), name='about'),
    # path('faq/', Faq.as_view(), name='faq'),
    # path('privacy/', Privacy.as_view(), name='privacy'),
    # path('terms/', Terms.as_view(), name='terms'),
    # path('disclaimer/', Disclaimer.as_view(), name='disclaimer'),
    # path('courses/', CourseList.as_view(), name='courses'),
    # path('courses/detail/', CourseDetail.as_view(), name='courses-detail'), 
    # path('contact/', Contact.as_view(), name='contact'),
    # path('registration/',include('registration.urls', namespace = 'registration')),
    path('contact/',include('contact.urls', namespace = 'contact')),    
    path("courses/", include("courses.urls", namespace = 'courses')),
    path("plans/", include("plans.urls", namespace = 'plans')),
    path("affiliates/", include("affiliates.urls", namespace = 'affiliates')),
    path('payments/',include('payments.urls', namespace = 'payments')), 
    path('dashboard/',include('dashboard.urls', namespace = 'dashboard')),
    path('coupon/',include('coupon.urls', namespace = 'coupon')),
    # path('coupons/',include('coupons.urls', namespace = 'coupons')),
    path('accounts/',include('accounts.urls', namespace = 'accounts')),
    path('accounts/', include('django.contrib.auth.urls'), name='accounts'), #auth library
    # urls handling WYSIWYG editor
    path('summernote/', include('django_summernote.urls')), 
    path('ns-admin/', admin.site.urls),
    path("", include("core.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

contact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from .views import contact, contact_sent#, quote_request, providers_registration, providers_registration_sent
# from authcode.views import home as pacg
# from capitation.views import home as cpar

app_name = 'contact'

urlpatterns = [
    path('', contact, name="contact"),
    path('sent/', contact_sent, name="contact-sent"),
    # path(r'quote-request/', quote_request, name="quote_request"),
    # path(r'providers/registration/', providers_registration, name="providers_registration"),
    # path(r'providers/registration/sent/', providers_registration_sent, name="providers_registration_sent"),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from .views import home_view, about_view, privacy_view, terms_view, disclaimer_view, sales_page_view, channel_page_view #Home, AboutUs, Privacy, Terms, Disclaimer#, CourseList, CourseDetail



urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('privacy/', privacy_view, name='privacy'),
    path('terms/', terms_view, name='terms'),
    path('disclaimer/', disclaimer_view, name='disclaimer'),
    path('community/', sales_page_view, name='sales_page'),
    path('channel/', channel_page_view, name='channel_page'),

    # path("programs/", include("courses.urls")),
    # path('about/', AboutUs.as_view(), name='about'),
    # path('faq/', Faq.as_view(), name='faq'),
    # path('privacy/', Privacy.as_view(), name='privacy'),
    # path('terms/', Terms.as_view(), name='terms'),
    # path('disclaimer/', Disclaimer.as_view(), name='disclaimer'),
    # path('contact/',include('contact.urls', namespace = 'contact')),
    
    # path("programs/", include("courses.urls", namespace = 'courses')),
    # path('courses/', CourseList.as_view(), name='courses'),
    # path('courses/detail/', CourseDetail.as_view(), name='courses-detail'),
    # path('dashboard/', home, name="dashboard"),    
    # path('contact/', Contact.as_view(), name='contact'),
    # path('accounts/',include('accounts.urls', namespace = 'accounts')),
    # path('registration/',include('registration.urls', namespace = 'registration')),
    # path('accounts/', include('django.contrib.auth.urls'), name='accounts'),
    # path('ns-admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from .views import plans_view

app_name = 'plans'

urlpatterns = [
       path('list/', plans_view, name='list'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect


from .forms import ContactForm#, QuoteRequestForm, ProvidersRegistrationForm
# from posts.models import Post, Tag


def contact(request):
    # queryset = Post.objects.active()
    c_form = ContactForm(request.POST or None)

    if request.method == "POST":
        if c_form.is_valid():
            form_fullname = c_form.cleaned_data.get("fullname")
            # form_lastname = c_form.cleaned_data.get("lastname")
            form_phone = c_form.cleaned_data.get("phone")
            form_email = c_form.cleaned_data.get("email")
            # form_company = c_form.cleaned_data.get("company")
            # form_subject = c_form.cleaned_data.get("subject")
            form_message = c_form.cleaned_data.get("message")

            subject = 'From cmetradingacademy.com (Contact Form):'  # %s %(form_subject)
            from_email = settings.DEFAULT_FROM_EMAIL
            to_email = ['dsixnine@gmail.com']
            contact_message = "\n fullname: %s \n Phone: %s \n Email: %s \n\n Message: \n %s" %(
                form_fullname,
                form_phone,
                form_email,
                # form_company,
                # form_subject,
                form_message)

            send_mail(subject,
                contact_message,
                from_email,
                to_email,
                fail_silently=False)
            context = {
                # "object_list": queryset,
                "c_form": c_form,
            }
            return HttpResponseRedirect('/contact/sent/')
            # return render(request, "contact.html", context)

    form_fullname = request.POST.get('fullname', '')
    # form_lastname = request.POST.get('lastname', '')
    form_phone = request.POST.get('phone', '')
    form_email = request.POST.get('email', '')
    # form_company = request.POST.get('company', '')
    # form_subject = request.POST.get('subject', '')
    form_message = request.POST.get('message', '')

    context = {
        # "object_list": queryset,
        "c_form": c_form,
        "fullname": form_fullname,
        # "lastname": form_lastname,
        "phone": form_phone,
        "email": form_email,
        # "company": form_company,
        # "subject": form_subject,
        "message": form_message,
    }
    return render(request, "contact/contact.html", context)





def contact_sent(request):
    c_form = ContactForm(request.POST or None)
    # contact_title = 'Your message has been sent. Thank you!'
    context = {
        "c_form": c_form,
    }
    return render(request, "contact/contact-sent.html", context)





# def quote_request(request):
#     # queryset = Post.objects.active()
#     c_form = QuoteRequestForm(request.POST or None)

#     if request.method == "POST":
#         if c_form.is_valid():
#             form_firstname = c_form.cleaned_data.get("firstname")
#             form_phone = c_form.cleaned_data.get("phone")
#             form_email = c_form.cleaned_data.get("email")
#             form_company = c_form.cleaned_data.get("company")
#             form_type_of_plan = c_form.cleaned_data.get("type_of_plan")
#             form_number_of_enrollee = c_form.cleaned_data.get("number_of_enrollee")
#             form_comment = c_form.cleaned_data.get("comment")

#             subject = 'From greenfieldhmo.com (Quote Request): %s' %('Quote Request')
#             from_email = settings.DEFAULT_FROM_EMAIL
#             to_email = ['contact@greenfieldhmo.com']
#             contact_message = " firstname: %s \n Phone: %s \n Email: %s \n Company: %s \n Type of plan: %s \n Number of enrollee: %s \n\n Comment: \n %s" %(
#                 form_firstname,
#                 form_phone,
#                 form_email,
#                 form_company,
#                 form_type_of_plan,
#                 form_number_of_enrollee,
#                 form_comment)

#             send_mail(subject,
#                 contact_message,
#                 from_email,
#                 to_email,
#                 fail_silently=False)
#             context = {
#                 # "object_list": queryset,
#                 "c_form": c_form,
#             }
#             return HttpResponseRedirect('/contact/message-sent/')
#             # return render(request, "contact.html", context)

#     form_firstname = request.POST.get('firstname', '')
#     form_phone = request.POST.get('phone', '')
#     form_email = request.POST.get('email', '')
#     form_company = request.POST.get('company', '')
#     form_type_of_plan = request.POST.get('type_of_plan', '')
#     form_number_of_enrollee = request.POST.get('number_of_enrollee', '')
#     form_comment = request.POST.get('comment', '')

#     context = {
#         # "object_list": queryset,
#         "c_form": c_form,
#         "firstname": form_firstname,
#         "phone": form_phone,
#         "email": form_email,
#         "company": form_company,
#         "type_of_plan": form_type_of_plan,
#         "number_of_enrollee": form_number_of_enrollee,
#         "comment": form_comment,
#     }
#     return render(request, 'home/contact/quote-request.html', context)






# # PROVIDER REGISTRATION

# def providers_registration(request):
#     # queryset = Post.objects.active()
#     c_form = ProvidersRegistrationForm(request.POST or None)

#     if request.method == "POST":
#         if c_form.is_valid():
#             form_title = c_form.cleaned_data.get("title")
#             form_firstname = c_form.cleaned_data.get("firstname")
#             form_lastname = c_form.cleaned_data.get("lastname")
#             form_email = c_form.cleaned_data.get("email")
#             form_phone = c_form.cleaned_data.get("phone")
#             form_phone2 = c_form.cleaned_data.get("phone2")
#             form_hospital = c_form.cleaned_data.get("hospital")
#             form_hospital_date = c_form.cleaned_data.get("hospital_date")
#             form_address = c_form.cleaned_data.get("address")
#             form_city = c_form.cleaned_data.get("city")
#             form_lga = c_form.cleaned_data.get("lga")
#             form_state = c_form.cleaned_data.get("state")
#             form_comment = c_form.cleaned_data.get("comment")

#             subject = 'From greenfieldhmo.com (Provider Reg.): %s' %('Provider Registration')
#             from_email = settings.DEFAULT_FROM_EMAIL
#             to_email = ['contact@greenfieldhmo.com']
#             contact_message = " Title: %s \n Full firstname: %s %s \n Phone: %s \n Mobile: %s \n Email: %s \n Hospital firstname: %s \n Hospital Date of Establishment: %s \n Address: %s \n City: %s \n L.G.A: %s \n State: %s \n\n Comment: \n %s" %(
#                 form_title,
#                 form_firstname,
#                 form_lastname,
#                 form_phone,
#                 form_phone2,
#                 form_email,
#                 form_hospital,
#                 form_hospital_date,
#                 form_address,
#                 form_city,
#                 form_lga,
#                 form_state,
#                 form_comment)

#             send_mail(subject,
#                 contact_message,
#                 from_email,
#                 to_email,
#                 fail_silently=False)
#             context = {
#                 # "object_list": queryset,
#                 "c_form": c_form,
#             }
#             return HttpResponseRedirect('/contact/providers/registration/sent/')
#             # return render(request, "contact.html", context)

#     form_title = request.POST.get('title', '')
#     form_firstname = request.POST.get('firstname', '')
#     form_lastname = request.POST.get('lastname', '')
#     form_email = request.POST.get('email', '')
#     form_phone = request.POST.get('phone', '')
#     form_phone2 = request.POST.get('phone2', '')
#     form_hospital = request.POST.get('hospital', '')
#     form_hospital_date = request.POST.get('hospital_date', '')
#     form_address = request.POST.get('address', '')
#     form_city = request.POST.get('city', '')
#     form_lga = request.POST.get('lga', '')
#     form_state = request.POST.get('state', '')
#     form_comment = request.POST.get('comment', '')

#     context = {
#         # "object_list": queryset,
#         "c_form": c_form,
#         "title": form_title,
#         "firstname": form_firstname,
#         "lastname": form_lastname,
#         "email": form_email,
#         "phone": form_phone,
#         "phone2": form_phone2,
#         "hospital": form_hospital,
#         "hospital_date": form_hospital_date,
#         "address": form_address,
#         "city": form_city,
#         "lga": form_lga,
#         "state": form_state,
#         "comment": form_comment,
#     }
#     return render(request, 'home/contact/providers-registration.html', context)







# def providers_registration_sent(request):
#     c_form = ContactForm(request.POST or None)
#     # contact_title = 'Your message has been sent. Thank you!'
#     context = {
#         "c_form": c_form,
#     }
#     return render(request, "home/contact/providers-registration-sent.html", context)





templates/inlines/about-affiliate.html
{% load i18n %}
{% load static %}
{% load humanize %}




    <div class="section about-us" id="about">
      <div class="container">
        <div class="row">
          <div class="col-md-5 order-sm-2 align-self-center">
            <div class="section-heading">
              <h6>About Us</h6>
              <h2>What make us the best trading academy?</h2>
              <p>We introduce people to the world of trading crypto through our non-drowsy educational content and tools. We're also a community of traders that support each other on our daily trading journey.</p>
            </div>
          </div>
          <div class="col-md-6 order-sm-1 offset-md-1">
            <div class="accordion" id="accordionExample">
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                  <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                    What is the CME affiliate network?
                  </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    CME Affiliate network is an affiliate marketing platform with over 10,000 qualified affiliates. Anyone can sign up on CME's affiliate network, pick a product from our over 70,000 products on CME, start selling it and you get a commission for every sale you make.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingTwo">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    How is commission determined?
                  </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    Creators on CME determine how much they want affiliates to earn from their product. The affiliate commission is usually between 10% - 50%.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingThree">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    How can I join the affiliate network?
                  </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    To join the affiliate network, you just have to make a yearly commission of &#8358;2,400. With this you get access to the affiliate network to promote. Click here to join the affiliate network.
                  </div>
                </div>
              </div>
              <div class="accordion-item">
                <h2 class="accordion-header" id="headingFour">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    How soon can I receive my payout?
                  </button>
                </h2>
                <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
                  <div class="accordion-body">
                    You don’t have to wait every Friday for your payout. For NGN payment, you get your payout 24hrs after a sale has been made, for USD.</code>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

   

templates/inlines/contact.html
{% load static %}


<div class="contact-us section" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-6  align-self-center">
          <div class="section-heading">
            <h6>Contact Us</h6>
            <h2>Feel free to contact us anytime</h2>
            <p>We introduce people to the world of trading crypto through our non-drowsy educational content and tools. We're also a community of traders that support each other on our daily trading journey.</p>
            <br><br>
            <!-- <div class="special-offer">
              <span class="offer">off<br><em>50%</em></span>
              <h6>Valid: <em>04 July 2024</em></h6>
              <h4>Special Offer <em>50%</em> OFF!</h4>
              <a href="#"><i class="fa fa-angle-right"></i></a>
            </div> -->
          </div>
        </div>
        <div class="col-lg-6">
          <div class="contact-us-content">
            <form id="contact-form" method="POST" action="{% url 'contact:contact' %}">{% csrf_token %}
              <div class="row">
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="fullname" id="fullname" value="{{ fullname }}" placeholder="Full name" autocomplete="on" required>
                    <span class="small text-white"><i>{{ c_form.fullname.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="phone" id="phone" value="{{ phone }}" pattern="+234" placeholder="Phone number" required="">
                    <span class="small text-white"><i>{{ c_form.phone.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <input type="text" name="email" id="email" value="{{ email }}" pattern="[^ @]*@[^ @]*" placeholder="E-mail address" required="">
                    <span class="small text-white"><i>{{ c_form.email.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <textarea name="message" id="message" placeholder="Your Message">{{ message }}</textarea>
                    <span class="small text-white"><i>{{ c_form.message.errors }}</i></span>
                  </fieldset>
                </div>
                <div class="col-lg-12">
                  <fieldset class="mb-4">
                    <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                  </fieldset>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/inlines/counter.html
{% load static %}


  <!-- <div class="section fun-facts" style="padding-top: 70px;"> -->
  <div class="section fun-facts">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="wrapper">
            <div class="row">
              <div class="col-lg-3 col-md-6">
                <div class="counter">
                  <h2 class="timer count-title count-number" data-to="804" data-speed="1000"></h2>
                  <p class="count-text ">Course Hours</p>
                </div>
              </div>
              <div class="col-lg-3 col-md-6">
                <div class="counter">
                  <h2 class="timer count-title count-number" data-to="250000" data-speed="1000"></h2>
                   <p class="count-text ">Happy Members</p>
                </div>
              </div>
              <div class="col-lg-3 col-md-6">
                <div class="counter">
                  <h2 class="timer count-title count-number" data-to="40" data-speed="1000"></h2>
                  <p class="count-text ">Partners</p>
                </div>
              </div>
              <div class="col-lg-3 col-md-6">
                <div class="counter end">
                  <h2 class="timer count-title count-number" data-to="15" data-speed="1000"></h2>
                  <p class="count-text ">Years Experience</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

templates/inlines/footer.html
{% load static %}


<footer class="section"> 
	<div class="container">
	  <div class="col-lg-12">
	    <p>&copy; <script>document.write(new Date().getFullYear());</script> CME Academy. &nbsp;|&nbsp; <span class="small"><a href="{% url 'terms' %}" rel="nofollow">Terms</a> &nbsp;|&nbsp; <a href="{% url 'privacy' %}" rel="nofollow">Policy</a> &nbsp;|&nbsp; <a href="{% url 'disclaimer' %}" rel="nofollow">Disclaimer</a>.</span> <br> Design&nbsp;by&nbsp;<a href="https://www.nakasoft.net" rel="nofollow" target="_blank">Nakasoft</a></p>
	  </div>
	</div>
</footer>
 

templates/inlines/header-pages.html
{% load static %}


  {% include 'inlines/navbar.html' %}


  <div class="main-banner" id="top">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          
        </div>
      </div>
    </div>
  </div>

templates/inlines/navbar-0.html
{% load static %}


<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                  <!-- ***** Logo Start ***** -->
                  <a href="{% url 'home' %}" class="logo">
                      <h1>CME&nbsp;Academy</h1>
                  </a>
                  <ul class="nav">
                    <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
                    <!-- <li class="scroll-to-section"><a href="#about">About</a></li> -->
                    {% if request.user.is_authenticated %}
                    <li class="scroll-to-section"><a class="{% if '/courses/' in request.path  %}active{% endif %}" href="{% url 'courses:list' %}">Courses</a></li>
                    {% endif %}
                    <li class="scroll-to-section"><a class="{% if '/plans/' in request.path  %}active{% endif %}" href="{% url 'plans:list' %}">CME Plans</a></li>
                    <li class="scroll-to-section"><a class="{% if '/affiliates/' in request.path  %}active{% endif %}" href="{% url 'affiliates:list' %}">Become CME Affiliate</a></li>
                    <li class="scroll-to-section"><a href="#contact">Contact</a></li>
                    
                    {% if request.user.is_authenticated %} 
                    <li>                     
                      <div class="main-button">
                        <a class="text-orange" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out"></i> Logout</a>
                      </div>
                    </li>
                    {% else %}
                    <li>
                      <a class="text-default" href="{% url 'accounts:login' %}"><i class="fa fa-sign-in"></i> Login</a>
                    </li>
                    <li>
                      <div class="main-button">
                        <a class="text-dark" href="{% url 'accounts:register' %}">Register</a>
                      </div>
                    </li>
                    {% endif %}
                  </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>

templates/inlines/navbar.html
{% load static %}



<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="{% url 'home' %}" class="logo">
                        <h1>CME&nbsp;Academy</h1>
                    </a>
                    <ul class="nav">
                        <li><a class="{% if request.path == '/' %}active{% endif %}" href="{% url 'home' %}">Home</a></li>
                        <!-- {#<li><a class="{% if '/about/' in request.path  %}active{% endif %}" href="{% url 'about' %}">About</a></li>#} -->
                        <!-- {#{% if request.user.is_authenticated %}
                        <li><a class="{% if '/courses/' in request.path  %}active{% endif %}" href="{% url 'courses:list' %}">Courses</a></li>
                        {% endif %}#} -->
                        <li><a class="{% if '/plans/' in request.path  %}active{% endif %}" href="{% url 'plans:list' %}">CME Plans</a></li>
                        <li><a class="{% if '/affiliates/' in request.path  %}active{% endif %}" href="{% url 'affiliates:list' %}">Become CME Affiliate</a></li>
                        <!-- {# <li><a class="{% if '/contact/' in request.path  %}active{% endif %}" href="{% url 'contact:contact' %}">Contact</a></li>  #} -->
                        {% if request.user.is_authenticated %} 
                        <li>
                          <div class="main-button">
                            <a class="text-primary" href="{% url 'dashboard:home' %}">Dashboard</a>
                          </div>
                        </li>
                        <li>
                          <div class="main-button">
                            <a class="text-danger" href="{% url 'accounts:logout' %}">Logout</a>
                          </div>
                        </li>
                        {% else %}
                        <li>
                          <a class="text-default" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                        <li>
                          <div class="main-button">
                            <a class="text-orange" href="{% url 'accounts:register' %}">Register</a>
                          </div>
                        </li>
                        {% endif %}
                    </ul>   
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>